# 继承 官方node image
FROM node:8.9.0  

# 拷贝 所有文件 到 app目录
COPY . /app

# 指定 app目录 为工作目录
WORKDIR /app

# 安装依赖 所有依赖 将打包到 image 文件
RUN ["yarn", "--registry=https://registry.npm.taobao.org"]

# 允许外包连接这个端口
EXPOSE 8080